---
- name: ANSIBLE COVERAGE SECTIONS
  hosts: ctr1
  vars:
    interfaces:
      - {port: FastEthernet0/0, prefix: 10.1.1.0/24}
      - {port: FastEthernet0/1, prefix: 10.1.2.0/24}
  tasts:
    - name: GENERATING THE INTERFACE CONFIGURATIONS.
      blockinfile:
        block: |
          hostname {{hostname | upper}}
          {% for intf in interfaces %}
          !
          interface{{intf.port}}
          ip address {{intf.prefix  | ipv4(1) | ipv4('address')}}{{intf.prefix | ipv4('netmask')}}
          !
          {% endfor %}
        dest: "configs/csr1_interfaces.cfg"
        create: yes
      delegate_to: localhost
